# This is a basic workflow to help you get started with Actions

name: Windows CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      
      # Runs a single command using the runners shell
      - name: Gathering information
        run: |
          systeminfo
      
      # Runs a single command using the runners shell
      - name: Installing Choco Package manager
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          
      # Runs a single command using the runners shell
      - name: Installing CLang12
        run: |
          choco install llvm
          clang --version
          
      # Runs a single command using the runners shell
      - name: Installing Ninja
        run: |
          choco install ninja
          ninja --version
          
      # Runs a single command using the runners shell
      - name: Installing Meson
        run: |
          choco install meson
          refreshenv
          meson --version
        

      # Runs a set of commands using the runners shell
      - name: Setup compiler workspace
        run: |
          meson setup build
          dir
          
      # Runs a set of commands using the runners shell
      - name: Compile
        run: |
          meson compile -C build
